theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Wiki Fluff Radio
description: Documentation and setup guides for stream animators
show_downloads: false
